[package]
name = "numerics"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
anyhow = "1.0.44"
thiserror = "1.0.29"

[[example]]
name = "spline1d"
path = "examples/spline1d.rs"